AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  certbot

  Sample SAM Template for certbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        WEBEX_HOOK_KEY: removed
        WEBEX_TEAMS_ACCESS_TOKEN: removed
        WEBEX_TEAMS_DEV_TOKEN: removed

Resources:
  CertBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: certbot/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 20
      Events:
        CertBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /certbot
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CertBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Cert Bot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/certbot/"
  CertBotFunction:
    Description: "Cert Bot Lambda Function ARN"
    Value: !GetAtt CertBotFunction.Arn
  CertBotFunctionIamRole:
    Description: "Implicit IAM Role created for Cert Bot function"
    Value: !GetAtt CertBotFunctionRole.Arn
